ARG RUBY_VERSION=3.3.4

FROM docker.io/library/ruby:$RUBY_VERSION

RUN apt update -qq && \
    apt install -y nodejs npm postgresql-client

WORKDIR /app

COPY Gemfile /app/Gemfile
COPY Gemfile.lock /app/Gemfile.lock

ENV RAILS_ENV=development
ENV BUNDLE_PATH=/usr/local/bundle

RUN bundle install

CMD ["bundle", "exec", "rails", "server", "-b", "0.0.0.0"]
